### ISSUE TITLE
Layer Description defined in CSV layer doesn't show clickable info icon in Data Library, even when correctly defined in CSV layers

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#202] opened 2021-01-08 10:40 UTC
Redlining Map for US Cities in golden has icon:
<img src="https://user-images.githubusercontent.com/324851/104004858-4626c680-5172-11eb-932d-76b6bf051cff.png" height=500>

Same in staging has no icon:
<img src="https://user-images.githubusercontent.com/324851/104005431-17f5b680-5173-11eb-8a33-213a31d2b31e.png" height=500>

Layer Description is correct in spreadsheet definition (no duplicate) and api.earthtime.org is correctly reporting the description:

<img src="https://user-images.githubusercontent.com/324851/104005010-82f2bd80-5172-11eb-918c-bd5831ba1660.png" height=300>

**Comment by jjkohler** [comment] 2021-01-21 19:52
Duplicate of #185

**Closed** 2021-01-21 19:54 UTC
Labels: Refactor
