### ISSUE TITLE
Active timeline affects playback rate used

### ISSUE THREAD

**Issue by pdille** [CMU-CREATE-Lab/data-visualization-tools#192] opened 2020-12-11 20:44 UTC
The order of layers being turned on (manually or the order in the share link) will affect what playback rate is used.

For example:

https://staging.earthtime.org/explore#v=30.04948,13.57429,0.457,latLng&t=1.08&ps=100&l=bdrk,sp_2018_gumcr_flow,sp_2018_global_umcr_for_bmi_2&bt=20180101&et=20281231&startDwell=0&endDwell=0

vs

https://staging.earthtime.org/explore#v=30.04948,13.57429,0.457,latLng&t=1.08&ps=100&l=bdrk,sp_2018_global_umcr_for_bmi_2,sp_2018_gumcr_flow&bt=20180101&et=20281231&startDwell=0&endDwell=0

In the first case, the **sp_2018_global_umcr_for_bmi_2** (which is listed last) has its playback rates set, whereas in the second the playback rate of **sp_2018_gumcr_flow** is used.

Note that **sp_2018_gumcr_flow** has a special playback rate and **sp_2018_global_umcr_for_bmi_2** uses default playback rate.

If you test both these combos on the golden URL, you will see that the playback rate of **sp_2018_gumcr_flow** is used in both cases and the animation is not playing back at warp speed. Previously we would only change playback rates when a layer with a non-default value was turned on. Now though, we loop through layers in reverse order to find the first one with the timeline we want to show and use its associated playback rate values. We thus can get different playback rates depending upon layer order.

Do we instead want to use the last layer turned on that does not have a non-default playback rate? Or do we accept that because we are showing a timeline we use whatever playback rate is associated with it?

@rsargent @gabrielo @jjkohler

**Comment by jjkohler** [comment] 2020-12-16 16:38
Wait until regression test includes speed and this will be revisited in 2021.

**Comment by jjkohler** [comment] 2021-01-04 22:13
@hjhawkinsiv has now added a field to testing, showing if current staging layers differ in playback speed from their golden counterparts. Initial review of 400 top layers revealed that 120 of them were impacted by differences in playback speed of varying amounts. If this ratio of 1/3 of layers holds through the rest of the layers, it means we'd have about 850 impacted waypoints.
@rsargent @pdille @gabrielo

**Comment by jjkohler** [comment] 2021-01-06 15:17
Another Example:

With current layer order in sharelink:
https://staging.earthtime.org/explore#v=34.53838,38.2796,4.798,latLng&t=1.00&ps=50&l=bdrk,ar,uf&bt=20100101&et=20121231&startDwell=0&endDwell=0

Proper behavior when layers are re-organized:
https://staging.earthtime.org/explore#v=34.53838,38.2796,4.798,latLng&t=1.00&ps=50&l=bdrk,uf,ar&bt=20100101&et=20121231&startDwell=0&endDwell=0

**Comment by rsargent** [comment] 2021-01-06 15:36
Waypoint 72:

![image](https://user-images.githubusercontent.com/324851/103786237-355b4100-500a-11eb-833d-ef9fabfc3cfb.png)

When clicking on waypoint 72 in golden vs staging, both show up as "Slow" by default and have same speeds.

Regression testing seems to instead show Medium speed for staging, as does following the regression testing link
![image](https://user-images.githubusercontent.com/324851/103786783-d2b67500-500a-11eb-881e-74674007c96d.png)

The link that shows medium in staging has ps=25, which should be slow, but produces medium in staging.  (Similar link correctly produces slow in golden)

https://staging.earthtime.org/explore#v=39.68237,-97.4215,2.248,latLng&t=0.38&startDwell=0&endDwell=1.0ps&l=bdrk,sp&bt=19840101&et=20161231&ps=25

**Comment by rsargent** [comment] 2021-01-06 15:47
Waypoint 206 is due to ps=XX not being honored

https://golden.earthtime.org/explore#v=40.4479,-79.94045,10.5,latLng&t=5&ps=15&l=bdrk,bdrk_detailed,allegheny_county_pgh,anim_acs_poverty_by_race_2010_2018&bt=20100101&et=20180101&startDwell=0&endDwell=0.02
is slow and

https://staging.earthtime.org/explore#v=40.4479,-79.94045,10.5,latLng&t=5&ps=15&l=bdrk,bdrk_detailed,allegheny_county_pgh,anim_acs_poverty_by_race_2010_2018&bt=20100101&et=20180101&startDwell=0&endDwell=0.02
is too fast because ps=15 is not honored.

**Comment by jjkohler** [comment] 2021-01-06 15:53
Original Golden behavior - reasonable speed movers:
https://golden.earthtime.org/explore#v=40.44532,-79.93235,9.72,latLng&t=0.50&ps=300&l=bdrk,bdrk_detailed,allegheny_county_pgh,voting_ac_freq_movers_4,voting_ac_freq_num_moves_4_epoch&bt=20100101&et=20181017&startDwell=0.5&endDwell=1.0

Extreme high speeds in staging:
https://staging.earthtime.org/explore#v=40.44532,-79.93235,9.72,latLng&t=0.50&ps=300&l=bdrk,bdrk_detailed,allegheny_county_pgh,voting_ac_freq_movers_4,voting_ac_freq_num_moves_4_epoch&bt=20100101&et=20181017&startDwell=0.5&endDwell=1.0

Until layers are reversed in the link. Now speed is closer to correct by VERY slow. This seems to be due to the other issue of PS not being honored in links:
https://staging.earthtime.org/explore#v=40.44532,-79.93235,9.72,latLng&t=0.50&ps=300&l=bdrk,bdrk_detailed,allegheny_county_pgh,voting_ac_freq_num_moves_4_epoch,voting_ac_freq_movers_4&bt=20100101&et=20181017&startDwell=0.5&endDwell=1.0

**Comment by rsargent** [comment] 2021-01-06 15:57
Split ps=XX bug off into #200

**Comment by pdille** [comment] 2021-01-06 23:05
While I was fixing issue 200 I went ahead and addressed this too. Fixed in commit ebf0e22

Please confirm.

**Comment by jjkohler** [comment] 2021-01-13 15:18
This appears to be fixed in most functional situations. Remaining diffs are showing only in layers with time frozen, meaning no difference of experience for viewers. Hence, closing this issue unless new examples of regressed visible experience emerge.

**Closed by jjkohler** 2021-01-13 15:18 UTC
Labels: Critical for Release, Refactor, close-after-confirm
