### ISSUE TITLE
Timeline weirdness in vs out of story for Urban Fragility

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#94] opened 2019-10-08 10:40 UTC
To reproduce:

Visit https://earthtime.org/stories/internallayers#waypointIdx=70&waypoints=1dxJ2YR3MFYTyZrV3MiGsm7kbOGPdvlzHL0_8HXhT7Bo.1596808134

Observe Fragile Score layer shows, with timeline 2000-2015

Zoom in until "Resume Story / Exit Story" appears

Click on "uf" waypoint

Observe Fragile Score layer shows, with incorrect timeline 1984-2016

**Comment by pdille** [comment] 2020-05-16 16:51
Note that once this layer is no longer a hardcoded layer this problem should no longer occur. The waypoint list in the link above appears to behave as intended with the refactor branch, so that's good news.

Leaving this open until that branch gets pulled back into main.

**Comment by pdille** [comment] 2021-05-12 18:39
Confirmed fixed now that main site uses latest code.

**Closed by pdille** 2021-05-12 18:39 UTC
Labels: awaiting-new-timeline, bug, high-priority
