### ISSUE TITLE
Improve performance of spinner management

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#41] opened 2018-12-01 04:57 UTC
Spinner management code, such as WebGLVectorTile2._removeLoadingSpinner and WebglMapTile._removeLoadingSpinner, slows image tile loading by factor of three, due to the complex dom search.  It would be better to manage the spinner without use of the dom.

**Comment by pdille** [comment] 2018-12-01 19:11
How are you measuring the speed?

Also, you mentioning raster image tile loading reminds me of an issue @gabrielo saw where every time an image tile is brought in additional legend elements are added to the DOM. I wonder if this is actually the slowdown you're seeing, since you could get hundreds of additions to the DOM from just a short time of panning/zooming. I can't seem do reproduce this though. @gabrielo can you confirm again the legend issue you showed me awhile back?

**Comment by rsargent** [comment] 2018-12-02 08:47
In chrome, using the performance timeline, it looks like texture loading takes about 1ms per tile and the DOM selector takes about 2ms per tile, for a total of 3ms.  FPS goes down to maybe 5-10 when level changes and lots of tiles are loaded, due to CPU, so removing the DOM selector could significantly reduce jank.

But looking more closely, sometimes it looks like the lion's share is in the querySelectorAll and sometimes not.  It seems where "Image Decode" lands might make the difference, so maybe the querySelectorAll is more like 1/3 of the slowness not 2/3?

![image](https://user-images.githubusercontent.com/324851/49337586-6ecb5200-f5e3-11e8-8777-9826df92a3a1.png)

vs

![image](https://user-images.githubusercontent.com/324851/49337593-a508d180-f5e3-11e8-85e0-f9f15ebd8d49.png)

(I'm surprised that Image Decode is even blocking the main thread, or happening during querySelectorAll)

**Comment by rsargent** [comment] 2018-12-02 09:43
Here's a bottom-up perf from a janky time:

![image](https://user-images.githubusercontent.com/324851/49338192-80652780-f5ec-11e8-9a11-7ee64d08b9b6.png)

Overall it looks like around 22% or 29% of time.  I'm still unclear why image decode sometimes appears as a subcall.

**Comment by rsargent** [comment] 2020-05-20 09:56
Let's look at this again and confirm after new-timeline is done.

**Comment by rsargent** [comment] 2021-05-12 18:35
Looks like spinner DOM management still takes 2/3 - 3/4 of the CPU for tile loading, using bdrk.  Paul and I propose a simpler spinner management might get rid of the per-tile operational cost here.

**Comment by rsargent** [comment] 2021-05-12 18:42
Simpler spinner management may also fix #111 , #31

**Comment by pdille** [comment] 2021-06-11 22:07
Addressed in commit 83860da

**Closed by pdille** 2021-06-11 22:07 UTC
Labels: bug, high-priority
